# Use root/example as user/password credentials

services:

  db:
    image: mariadb:latest
    container_name: sparkcode-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: suwon-bus-db
      MARIADB_USER: root
      MARIADB_PASSWORD: example
    ports:
      - 13306:3306
    volumes:
      - ./db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080

volumes:
  db_data:
    driver: local